### PR TITLE
feat(cli): Added  Subcommand dmmf_file_to_dml

### PR DESCRIPTION
**Pull request by williamluke4**
Fixes deserialization issues with dmmf_to_dml

Related to 
- https://github.com/prisma/prisma2/issues/254
- https://github.com/prisma/prisma2/issues/807

```bash
prisma cli --dmmf_file_to_dml /tmp/dmmf.json
```
```prisma2 convert``` 
Would have to be changed to use 
```prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf_file_to_dml /tmp/dmmf.json``` 
As oppose to 
```prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf_to_dml {"config":{"datasources":[], "generators":[]},"dmmf":"{\"models\":........```

### CODE REVIEW

**Comment by pimeys** [comment]
Squash and rebase before merging.

Please be aware that the cli apis are not public and we can break them without announcing in the future.

**Comment by williamluke4** [comment]
@pimeys I'm going to close and submit another PR

**Comment by janpio** [comment]
Just a sidenote:

You can squash when merging via GitHub UI, just use the "Squash and merge" button instead of "Merge pull request" (via the dropdown in the button). It uses the GitHub PR title as the commit message, so this additional work technically would not have been necessary if this was about getting to one commit.

If an additional rebase was required, this was indeed the best way to get there.

**Comment by williamluke4** [comment]
@janpio Haha thanks for that 🙈 Ended up deleting my fork and recreating the branch 😂

**Pull request closed without merging**
